sudo: required

language: python

services:
  - docker

virtualenv:
  system_site_packages: true

python:
  - '2.7'

script:
  - ./build.sh
  - pushd sample/replication
  - make up
  - make status
  # Check for database status
  - until make check-master-running; do echo "Retrying"; sleep 5; done
  - until make check-slave-running; do echo "Retrying"; sleep 5; done
